### ISSUE TITLE
Las claves "theme" y "keyword" de todos los datasets en datos.gob.ar son mucho más largas de lo esperado

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/ckanext-datajsonar#1]
http://datos.gob.ar/data.json

Es difícil de entender con claridad cuál es el problema, pero pareciera ser que todos los datasets del portal (sean "originales" nuestros o federados de Justicia) tiene la misma lista de "keyword" y "theme":

"keyword": [

    "derechos-humanos",
    "desaparecidos",
    "desaparicion-forzada",
    "represion",
    "victimas",
    "derechos-humanos",
    "femicidios",
    "genero",
    "homicidios",
    "violencia",
    "asambleas",
    "asociaciones-civiles",
    "autoridades",
    "fundaciones",
    "igj",
    "personas-juridicas",
    "sistema-registral",
    "sociedades",
    "automotores",
    "iniciales",
    "inscripciones",
    "maquinarias",
    "motovehiculos",
    "prendas",
    "registracion",
    "sistema-registral",
    "transferencias",
    "carceles",
    "ejecucion-de-la-pena",
    "establecimientos-penitenciarios",
    "personas-privadas-de-la-libertad",
    "politica-criminal",
    "presos",
    "prision",
    "sistema-penitenciario",
    "sneep",
    "spf",
    "cargo",
    "concurso",
    "defensor",
    "federal",
    "fiscal",
    "juez",
    "justicia",
    "magistrado",
    "nacional",
    "organo",
    "poder-judicial",
    "subrogante",
    "vacante",
    "automotores",
    "maquinarias",
    "motovehiculos",
    "prendas",
    "registracion",
    "sistema-registral",
    "transferencias",
    "anmac",
    "armas",
    "legitimo-usuario",
    "portacion",
    "renar",
    "sistema-registral",
    "anmac",
    "armas",
    "portacion",
    "renar",
    "sistema-registral",
    "acordadas",
    "boletin-oficial",
    "decisiones-administrativas",
    "decretos",
    "disposiciones",
    "informacion-juridica",
    "leyes",
    "resoluciones",
    "denuncias",
    "derechos-humanos",
    "violacion-a-los-derechos-humanos",
    "violencia-institucional",
    "capturas",
    "detencion",
    "rebeldias",
    "sistema-registral",
    "acceso-a-justicia",
    "acceso-a-la-justicia",
    "asesoramiento-juridico",
    "caj",
    "casas-de-justicia",
    "justicia",
    "vulnerable",
    "boletin-oficial",
    "codigos-provinciales",
    "constituciones-provinciales",
    "decretos",
    "informacion-juridica",
    "leyes",
    "acordadas",
    "decisiones-administrativas",
    "decretos",
    "disposiciones",
    "informacion-juridica",
    "inteligencia-juridica",
    "leyes",
    "resoluciones",
    "tesauro-juridico",
    "vocabularios-controlados",
    "Economía",
    "Gastos",
    "Recursos",
    "acceso-a-justicia",
    "mediacion",
    "prejudicial",
    "resolucion-alternativa-de-conflictos",
    "condenados",
    "federal",
    "inimputables",
    "penitenciario",
    "presos",
    "prision",
    "procesados",
    "procesal",
    "sistema-penitenciario",
    "spf",
    "anticorrupcion",
    "ddjj",
    "etica-publica",
    "funcionarios",
    "ley-25188",
    "ley-26857",
    "patrimonio",
    "apertura",
    "compromisos",
    "datos",
    "gobierno abierto",
    "ministerios",
    "participación",
    "Alquileres",
    "Bienes inmuebles",
    "Contratos",
    "Inmuebles",
    "Locador",
    "Autoridades",
    "Cargos",
    "Estructuras",
    "Jerarquía",
    "Organigramas",
    "Comunicación",
    "Gastos",
    "Medios",
    "Pauta",
    "Publicidad",
    "Adjudicaciones",
    "Bienes",
    "Catálogo",
    "Compras",
    "Concursos",
    "Contrataciones",
    "Convocatorias",
    "Finanzas Públicas",
    "Gastos",
    "Presupuesto",
    "Proveedores",
    "Servicios",
    "Asignaciones",
    "Autoridades Superiores",
    "Estructura",
    "Salarios",
    "Sueldos",
    "Agendas",
    "Audiencias",
    "Funcionarios",
    "Registros",
    "Reuniones",
    "Acceso",
    "Decretos",
    "Pedidos",
    "Registros",
    "Solicitudes",
    "Trámites",
    "Contratos",
    "Empleo Público",
    "Nómina de Personal Contratado",
    "Organismos",
    "Personal"

],
"theme": [

    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Economía y finanzas",
    "Gobierno y sector público",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Justicia, seguridad y legales",
    "Gobierno y sector público",
    "Gobierno y sector público",
    "Gobierno y sector público",
    "Gobierno y sector público",
    "Economía y finanzas",
    "Gobierno y sector público",
    "Gobierno y sector público",
    "Gobierno y sector público",
    "Gobierno y sector público",
    "Gobierno y sector público"

]

**Comment by JoseSalgado1024** [comment]
Ya esta solucionado este ISSUE!
