### ISSUE TITLE
Discrepancias de nombres entre ckanext y el perfil de metadatos

### ISSUE THREAD

**Issue by lrromero** [datosgobar/ckanext-datajsonar#37]
De acuerdo al perfil de metadatos 1.1, hay campos de un dataset que se corresponden con campos extras de un paquete de CKAN. Estos campos se están guardando y leyendo con nombres que no respetan el perfil. Estos son:
- temporal como `dateRange`, debería ser `temporal`
- superTheme como `globalGroups`, debería ser `superTheme`
- accrualPeriodicty como `updateFrequency`, debería ser `accrualPeriodicity`

Estos cambios deberían coordinarse con el portal andino para que los comience a guardar de manera correcta.

**Comment by poligarcia** [comment]
Para resolver el problema del los keys mal mapeados en instancias actuales de andino hay que crear una migración de datos que renombre los keys de los extra usados en el perfil de metadatos

cc @lalo73
