### ISSUE TITLE
Corregir accessURL de las distribuciones

### ISSUE THREAD

**Issue by nsampi** [datosgobar/ckanext-datajsonar#8]
El campo accessURL muestra la misma url que downloadURL cuando estas no son necesariamente las mismas.
De acuerdo con el perfil de metadatos accessURL es la "URL que permite el acceso a la distribución del dataset. Puede ser una página, feed u otro tipo de recurso que dé acceso indirecto a las distribuciones. Si las distribuciones son solo accesibles a través de la página de referencia del dataset, debe completarse el valor de la URL de acceso a la distribución con el mismo valor de la página de referencia del dataset."
[Ejemplo](http://datos.gob.ar/dataset/sistema-de-contrataciones-electronicas-argentina-compra/archivo/fa3603b3-0af7-43cc-9da9-90a512217d8a)

**Comment by JoseSalgado1024** [comment]
Tomo este issues, inicialmente voy a trarar de diagnosticar el bug, para entender donde fue que el feature dejo de funcionar y en base a el/los problemas que detecte, crear una solucion

**Comment by JoseSalgado1024** [comment]
Encontre el error y esta solucionado, creo PR

**Comment by poligarcia** [comment]
El método utilizado en el PR no es válido, ya que no contempla los casos en los que el recurso/distribución haya sido creado usando la URL de un CSV no alojada en el sitio original.
